version: '3.9'

services:
  account:
    container_name: account
    build:
      dockerfile: Dockerfile
    command: sh -c "chmod +x wait-for-postgres.sh && ./wait-for-postgres.sh pgdb &&  make run"
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_HOST=pgdb
      - POSTGRES_USER=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=acc_db
    depends_on:
      - pgdb
      - redis
    restart: always
    networks:
      - backend
  
  pgdb:
    image: postgres:14.5
    container_name: pgdb
    ports:
      - "5436:5432"
    environment:
      - POSTGRES_HOST=pgdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=acc_db
      - PGDATA="/var/lib/postgresql/data/pgdata"
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
    restart: always
    networks:
      - backend

  redis:
    image: redis:7.0-alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
    networks:
      - backend

networks:
  backend:
    driver: bridge